spring.application.name=demo
server.port=8888

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://192.168.0.9:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ckwhdgus
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.baseline-on-migrate=true